# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site title and description
title:              Conductor
description:        Learn how to use your Conductor
lang:               en

# Site subpath, e.g. /blog
baseurl:            ""

# Permalink URLs structure, for permalink style options see: https://jekyllrb.com/docs/permalinks/
permalink:          /:categories/:title/

# Site base hostname & protocol, e.g. http://example.com
url:                ""

# Site logo # e.g. logo.png, upload logo image file to /uploads/ folder
logo:               
  
# Default author settings
author:
    name:           Felix Jen
    title:          Lead Engineer  
    avatar:         /fjlabs-logo.png

# Social icons displayed in footer
social:
    email:          felix@fjlaboratories.com
    website:        https://fjlaboratories.com/conductor
    facebook:       
    flickr:
    dribbble:
    github:         https://github.com/FJLabs-Designs/Conductor-Documentation
    googleplus:
    instagram:      https://www.instagram.com/fjlaboratories/
    linkedin:
    pinterest:
    twitter:        
    vimeo:          
    youtube:        https://www.youtube.com/channel/UCP8p1ypPg0hiJ9i84-0Y2Dw

# Share button
share:
    post:           false # Display share buttons on a post page
    twitter:        false # Enable by adding Twitter handle 
    facebook:       false # Enable by setting true (Facebook handle not required)

header:
  image: pattern.svg
  # background: "rgba(0, 0, 0, 0.5)"
  color: light
  search: true

# Default footer image settings
footer:
    copyright:      Made by <a href="https://fjlaboratories.com/">FJLaboratories</a> in Chicago!

# Google analytics code, get your code here https://www.google.com/analytics/
google_analytics:

# Pagination Settings
pagination:
  enabled:          true
  per_page:         6
  # permalink: '/page/:num/'
  # title_suffix: ' - page :num'
  # limit: 0
  sort_field: 'title'
  # sort_reverse: true

# Path to post content assets directory i.e post images, pdfs etc
uploads:            /uploads/

# Build settings
markdown:           kramdown
highlighter:        rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-avatar
  - jekyll-paginate-v2
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules

sass:
  style:            compressed

collections:
  faqs:
    output:         false
  changelogs:
    output:         false

# Defaults
defaults:
  # _posts
  - scope:
      path:         ""
      type:         posts
    values:
      layout:       post
  # _pages
  - scope:
      path:         ""
      type:         pages
    values:
      layout:       page